### ISSUE TITLE
Meteor always ends up failing on node-fibers

### ISSUE THREAD

**Issue by carlokok** [libreboard/libreboard#138]
I have tried several node versions (0.11.13, 0.11.16 and 0.12) but each time it ends up failing installing node-fibers@1.0.1

What am I doing wrong?
```
WARNING: The output directory is under your source tree.

npm WARN package.json meteor-dev-bundle@0.0.0 No description
npm WARN package.json meteor-dev-bundle@0.0.0 No repository field.
npm WARN package.json meteor-dev-bundle@0.0.0 No README data
-
> fibers@1.0.1 install /home/ck/libreboard/.build/bundle/programs/server/node_modules/fibers
> node ./build.js

child_process: customFds option is deprecated, use stdio instead.
child_process: customFds option is deprecated, use stdio instead.
make: Entering directory `/home/ck/libreboard/.build/bundle/programs/server/node_modules/fibers/build'
  CXX(target) Release/obj.target/fibers/src/fibers.o
../src/fibers.cc:222:34: error: 'Arguments' does not name a type
   static Handle<Value> New(const Arguments& args) {
                                  ^
../src/fibers.cc:222:45: error: ISO C++ forbids declaration of 'args' with no type [-fpermissive]
   static Handle<Value> New(const Arguments& args) {
                                             ^
../src/fibers.cc:241:34: error: 'Arguments' does not name a type
   static Handle<Value> Run(const Arguments& args) {
                                  ^
<SNIP 100 lines>

  ^
make: *** [Release/obj.target/fibers/src/fibers.o] Error 1
make: Leaving directory `/home/ck/libreboard/.build/bundle/programs/server/node_modules/fibers/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
gyp ERR! System Linux 3.13.0-44-generic
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/ck/libreboard/.build/bundle/programs/server/node_modules/fibers
gyp ERR! node -v v0.12.0
gyp ERR! node-gyp -v v1.0.2
gyp ERR! not ok
Build failed
npm ERR! Linux 3.13.0-44-generic
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE

npm ERR! fibers@1.0.1 install: `node ./build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the fibers@1.0.1 install script 'node ./build.js'.
npm ERR! This is most likely a problem with the fibers package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./build.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls fibers
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/ck/libreboard/.build/bundle/programs/server/npm-debug.log
```

**Comment by Slava** [comment]
I don't think node-fibers npm module was ported to node 0.12 yet. Try using node 0.10.

**Comment by carlokok** [comment]
ah that did it!

**Comment by sjmcdowall** [comment]
Or use fibers@1.0.5 which works (or seems to) for me on node 0.12

**Comment by kingmatusevich** [comment]
It keeps failing for me on 0.10.36

**Comment by sjmcdowall** [comment]
Are you sure you are specifying fibers@1.0.5 ??  That's the version of fibers that should work with node 0.10.36.

**Comment by sjmcdowall** [comment]
(well fibers@1.0.6 should work too)
