### ISSUE TITLE
Application crashing when building locally

### ISSUE THREAD

**Issue by natagoddanti** [libreboard/libreboard#156]
I was trying to build the new 'renaissance' wip release locally but the app is crashing and this is the stack report:

20150513-08:13:08.635(-7)? Meteor._wrapAsync has been renamed to Meteor.wrapAsync
I20150513-08:13:08.736(-7)? > Starting board-background-color migration.
W20150513-08:13:08.743(-7)? (STDERR)
W20150513-08:13:08.743(-7)? (STDERR) /Users/shekar/.meteor/packages/meteor-tool/.1.1.3.1d2103y++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:278
W20150513-08:13:08.743(-7)? (STDERR) 						throw(ex);
W20150513-08:13:08.743(-7)? (STDERR) 						      ^
W20150513-08:13:08.791(-7)? (STDERR) MongoError: multi update only works with $ operators
W20150513-08:13:08.792(-7)? (STDERR)     at Object.Future.wait (/Users/shekar/.meteor/packages/meteor-tool/.1.1.3.1d2103y++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:398:15)
W20150513-08:13:08.792(-7)? (STDERR)     at [object Object].<anonymous> (packages/meteor/helpers.js:119:1)
W20150513-08:13:08.792(-7)? (STDERR)     at [object Object].MongoConnection.(anonymous function) [as update] (packages/mongo/mongo_driver.js:678:1)
W20150513-08:13:08.792(-7)? (STDERR)     at Object.fields (packages/matb33:collection-hooks/update.js:75:1)
W20150513-08:13:08.792(-7)? (STDERR)     at Object.collection.(anonymous function) [as update] (packages/matb33:collection-hooks/collection-hooks.js:103:1)
W20150513-08:13:08.792(-7)? (STDERR)     at [object Object].Mongo.Collection.(anonymous function) (packages/mongo/collection.js:575:1)
W20150513-08:13:08.792(-7)? (STDERR)     at [object Object].Mongo.Collection.(anonymous function) [as update] (packages/aldeed:collection2/collection2.js:165:1)
W20150513-08:13:08.792(-7)? (STDERR)     at Object.Migrations.add._.forEach.Boards.update.permission [as board-background-color] (app/server/migrations.js:19:10)
W20150513-08:13:08.792(-7)? (STDERR)     at Package (packages/idmontie:migrations/idmontie:migrations.js:122:1)
W20150513-08:13:08.792(-7)? (STDERR)     at /Users/shekar/ActionBloks/actionbloks-renaissance/libreboard/.meteor/local/build/programs/server/boot.js:229:5
W20150513-08:13:08.792(-7)? (STDERR)     - - - - -
W20150513-08:13:08.792(-7)? (STDERR)     at Object.toError (/Users/shekar/.meteor/packages/mongo/.1.1.0.4sycj9++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/utils.js:114:11)
W20150513-08:13:08.793(-7)? (STDERR)     at /Users/shekar/.meteor/packages/mongo/.1.1.0.4sycj9++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/collection/core.js:577:27
W20150513-08:13:08.793(-7)? (STDERR)     at /Users/shekar/.meteor/packages/mongo/.1.1.0.4sycj9++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1195:7
W20150513-08:13:08.793(-7)? (STDERR)     at /Users/shekar/.meteor/packages/mongo/.1.1.0.4sycj9++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/db.js:1903:9
W20150513-08:13:08.793(-7)? (STDERR)     at Server.Base._callHandler (/Users/shekar/.meteor/packages/mongo/.1.1.0.4sycj9++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/base.js:453:41)
W20150513-08:13:08.793(-7)? (STDERR)     at /Users/shekar/.meteor/packages/mongo/.1.1.0.4sycj9++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:487:18
W20150513-08:13:08.793(-7)? (STDERR)     at [object Object].MongoReply.parseBody (/Users/shekar/.meteor/packages/mongo/.1.1.0.4sycj9++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
W20150513-08:13:08.793(-7)? (STDERR)     at [object Object].<anonymous> (/Users/shekar/.meteor/packages/mongo/.1.1.0.4sycj9++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/server.js:445:20)
W20150513-08:13:08.793(-7)? (STDERR)     at [object Object].emit (events.js:95:17)
W20150513-08:13:08.793(-7)? (STDERR)     at [object Object].<anonymous> (/Users/shekar/.meteor/packages/mongo/.1.1.0.4sycj9++os+web.browser+web.cordova/npm/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:207:13)
=> Exited with code: 8
=> Your application is crashing. Waiting for file change.

**Comment by natagoddanti** [comment]
As I was trying to debug the code, adding a new field in the board collection seems to be resolving the issue. So this is what I added to the board collection to match up the field defintions in   migrations. 

'background.type': {
        type: String,
        allowedValues: ['color']
    },
